import type { Settings } from "../../../_mock-data/modules/settings";


/**
 * Stores custom values for objects generated by backend.
 */
export class SettingsCache {
    private cache: Partial<Settings>
    
    constructor() {
        this.cache = {};
    }

    /**
     * Returns custom settings stored in cache.
     */
    get(): Partial<Settings> {
        return { ...this.cache };
    }

    /**
     * Updates cache with provided `customSettings`
     */
    update(customSettings: Partial<Settings>): void {
        this.cache = { ...this.cache, ...customSettings };
    }
}
