/**
 * Stores custom values for objects generated by backend.
 */
export class SettingsCache {
    constructor() {
        this.cache = {};
    }

    /**
     * Returns custom settings stored in cache.
     */
    get() {
        return { ...this.cache };
    }

    /**
     * Updates cache with provided `customSettings`
     */
    update(customSettings) {
        this.cache = { ...this.cache, customSettings };
    }
}
