import { ObjectsCache } from "./modules/objects";
import { SettingsCache } from "./modules/settings";
import { TagsCache } from "./modules/tags";
import { UsersCache } from "./modules/users";


/**
 * Stores custom values for data generated by backend
 */
export class BackendCache {
    constructor() {
        this.objects = new ObjectsCache();
        this.tags = new TagsCache();
        this.users = new UsersCache();

        this.settings = new SettingsCache();
    }
}
